# Generated by Django 4.1.7 on 2023-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card_no', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'master_table',
            },
        ),
        migrations.CreateModel(
            name='voter_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('Age', models.CharField(default=None, max_length=100, null=True)),
                ('Gender', models.CharField(default=None, max_length=100, null=True)),
                ('Address', models.CharField(default=None, max_length=100, null=True)),
                ('username', models.CharField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('confirm_password', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'voter_register',
            },
        ),
    ]
