# Generated by Django 4.1.7 on 2023-03-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_election_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default=None, max_length=100, null=True)),
                ('age', models.CharField(default=None, max_length=100, null=True)),
                ('gender', models.CharField(default=None, max_length=100, null=True)),
                ('political_party', models.CharField(default=None, max_length=100, null=True)),
                ('caste', models.CharField(default=None, max_length=100, null=True)),
                ('Address', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'candidate_detail',
            },
        ),
    ]
