# Generated by Django 4.1.7 on 2023-03-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_candidate_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter_register',
            old_name='name',
            new_name='voter_name',
        ),
    ]
