# Generated by Django 4.1.7 on 2023-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0010_rename_election_date_election_detail_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Block',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
