# Generated by Django 4.1.7 on 2023-03-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0011_vote_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Date',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
