# Generated by Django 4.1.7 on 2023-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0012_vote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Manipulation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
