# Generated by Django 4.1.7 on 2023-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0013_vote_manipulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Block',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
