# Generated by Django 4.1.7 on 2023-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0014_alter_vote_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_detail',
            name='Vote',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
