# Generated by Django 4.1.7 on 2023-10-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0015_candidate_detail_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Manipulation',
        ),
    ]
